[package]
name = "calendar"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.11.0"
axum = "0.4.5"
chrono = "0.4.19"
tokio = { version = "1.14.1", features = ["rt-multi-thread", "macros"] }
