[package]
name = "chronodates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11.0"
axum = "0.4.5"
chrono = "0.4.19"
tokio = { version = "1.0", features = ["full"] }
